extends: default

rules:
  line-length:
    max: 120
    level: warning

  indentation:
    spaces: 2
    indent-sequences: true
    check-multi-line-strings: false

  document-start:
    present: false

  truthy:
    allowed-values: ['true', 'false', 'on', 'off']

  comments:
    min-spaces-from-content: 1

  comments-indentation: enable

  empty-lines:
    max: 1
    max-start: 0
    max-end: 0

  trailing-spaces: enable

  key-duplicates: enable

  new-line-at-end-of-file: enable

  brackets:
    min-spaces-inside: 0
    max-spaces-inside: 1

  braces:
    min-spaces-inside: 0
    max-spaces-inside: 1

ignore: |
  node_modules/
  dist/
  build/
  .next/
  coverage/
  *.lock
  *.lockb
