name: CI

# Strict workflow configuration with security best practices
on:
  push:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]

# Cancel in-progress runs when a new commit is pushed
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

# Set default permissions to read-only for security
permissions:
  contents: read

# Default job configuration
defaults:
  run:
    shell: bash

jobs:
  ci:
    name: CI Checks
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions:
      contents: read
    strategy:
      matrix:
        task:
          - name: "Biome Check"
            command: "bun run biome:check"
          - name: "Type Check"
            command: "bun run typecheck"
          - name: "Test Coverage"
            command: "bun run test:coverage"
    steps:
      - name: Setup
        uses: ./.github/actions/setup
      - name: Run ${{ matrix.task.name }}
        run: ${{ matrix.task.command }}
